@echo off
setlocal enabledelayedexpansion

:: ========================================
::           D2GitSync v1.0
:: Diablo 2 Resurrected Save Synchronizer
:: ========================================

:: Check if running as administrator
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo [INFO] Requesting administrator privileges...
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

:: Change to script directory
cd /d "%~dp0"

:: ========================================
::           CONFIGURATION
:: ========================================
:: Update these paths for your setup:

:: Default Diablo 2 Resurrected saves location
set "SAVES_PATH=C:\Users\%USERNAME%\Saved Games\Diablo II Resurrected"

:: Where to store the git repository (customize as needed)
set "GIT_REPO_PATH=D:\D2RSaves"

:: Path to your D2R launcher executable
set "LAUNCHER_PATH=D2R.exe"

:: PowerShell watcher script (don't change unless you move the file)
set "WATCHER_SCRIPT=%~dp0D2SaveWatcher.ps1"

:: ========================================
::           STARTUP CHECKS
:: ========================================

echo.
echo ========================================
echo    D2GitSync - Save Synchronizer
echo ========================================
echo.

:: Check if saves directory exists
if not exist "%SAVES_PATH%" (
    echo [ERROR] Saves directory not found: %SAVES_PATH%
    echo [INFO]  Please update SAVES_PATH in this script to match your D2R saves location.
    echo [INFO]  Common locations:
    echo         - C:\Users\%USERNAME%\Saved Games\Diablo II Resurrected
    echo         - C:\Users\%USERNAME%\Documents\Diablo II Resurrected
    echo.
    pause
    exit /b 1
)

:: Check if launcher exists
if not exist "%LAUNCHER_PATH%" (
    echo [WARNING] Launcher not found: %LAUNCHER_PATH%
    echo [INFO]    Please update LAUNCHER_PATH in this script.
    echo [INFO]    Common names: D2R.exe, Diablo II Resurrected.exe, D2RLAN.exe
    echo [INFO]    You can continue without the launcher - saves will still sync.
    echo.
    set /p CONTINUE="Continue anyway? (y/n): "
    if /i not "!CONTINUE!"=="y" exit /b 1
    set "LAUNCHER_PATH="
)

:: ========================================
::        GIT REPOSITORY SETUP
:: ========================================

echo [INFO] Checking git repository...

:: Step 1: Initialize git repo if it doesn't exist
if not exist "%GIT_REPO_PATH%\.git" (
    echo [INFO] Setting up git repository for saves...
    if not exist "%GIT_REPO_PATH%" mkdir "%GIT_REPO_PATH%"
    cd /d "%GIT_REPO_PATH%"
    
    git init --initial-branch=main 2>nul
    if %errorlevel% neq 0 (
        echo [ERROR] Git not found. Please install Git for Windows.
        echo [INFO]  Download from: https://git-scm.com/download/win
        pause
        exit /b 1
    )
    
    echo # Diablo 2 Resurrected Save Files > README.md
    echo # Generated by D2GitSync >> README.md
    echo. >> README.md
    echo This repository contains automatically synchronized D2R save files. >> README.md
    
    :: Create .gitignore for temporary files
    echo *.tmp > .gitignore
    echo *.bak >> .gitignore
    echo *.ctlo >> .gitignore
    echo *.keyo >> .gitignore
    echo Settings.json >> .gitignore
    echo Thumbs.db >> .gitignore
    echo .DS_Store >> .gitignore
    
    git add .
    git commit -m "Initial commit: Setup D2R saves repository"
    
    echo.
    echo [SUCCESS] Git repository initialized at: %GIT_REPO_PATH%
    echo.
    echo [IMPORTANT] To sync across multiple computers, set up a remote repository:
    echo.
    echo   1. Create a repository on GitHub/GitLab (keep it private!)
    echo   2. Run these commands in the git directory:
    echo      cd "%GIT_REPO_PATH%"
    echo      git remote add origin YOUR_REPOSITORY_URL
    echo      git push -u origin main
    echo.
    pause
)

:: ========================================
::           SYNC FROM REMOTE
:: ========================================

echo [INFO] Checking for remote save updates...
cd /d "%GIT_REPO_PATH%"

git fetch origin 2>nul
if %errorlevel% equ 0 (
    echo [INFO] Pulling latest saves from remote...
    git pull origin main 2>nul
    if %errorlevel% neq 0 (
        echo [WARNING] Git pull failed. Continuing with local saves...
    ) else (
        echo [SUCCESS] Updated saves from remote repository
    )
) else (
    echo [INFO] No remote repository configured or connection failed.
    echo [INFO] Working with local saves only.
)

:: ========================================
::        COPY SAVES TO GAME DIR
:: ========================================

echo [INFO] Syncing saves to game directory...
xcopy "%GIT_REPO_PATH%" "%SAVES_PATH%" /E /Y /I /Q 2>nul
if %errorlevel% equ 0 (
    echo [SUCCESS] Saves synchronized to game directory
) else (
    echo [WARNING] Some files may not have copied correctly
)

:: ========================================
::        START FILE WATCHER
:: ========================================

echo [INFO] Starting save file monitor...
if exist "%WATCHER_SCRIPT%" (
    powershell -WindowStyle Hidden -ExecutionPolicy Bypass -File "%WATCHER_SCRIPT%" -SavesPath "%SAVES_PATH%" -GitRepoPath "%GIT_REPO_PATH%" >nul 2>&1 &
    echo [SUCCESS] File watcher started - saves will auto-sync while playing
) else (
    echo [ERROR] File watcher script not found: %WATCHER_SCRIPT%
    echo [WARNING] Saves will not auto-sync during gameplay
)

:: ========================================
::           LAUNCH GAME
:: ========================================

echo.
echo ========================================
if not "%LAUNCHER_PATH%"=="" (
    echo [INFO] Launching Diablo 2 Resurrected...
    start "" "%LAUNCHER_PATH%"
    echo [SUCCESS] Game launched successfully!
) else (
    echo [INFO] No launcher configured - please start D2R manually
)

echo.
echo [INFO] File monitoring is active in the background
echo [INFO] Your saves will be automatically backed up to git
echo [INFO] Close this window when done playing to stop monitoring
echo ========================================
echo.

pause

:: ========================================
::              CLEANUP
:: ========================================

echo [INFO] Stopping file watcher...
taskkill /f /im powershell.exe /fi "WINDOWTITLE eq D2SaveWatcher*" 2>nul >nul
echo [INFO] D2GitSync stopped. Have a great day!
timeout /t 2 >nul
